name: Pipeline

on: [push]
env:
  APPLICATION_NAME: startupapp
jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - name: Setup Python environment
      uses: actions/setup-python@v4
    - name: Install requirements
      run: pip install --quiet --requirement requirements.txt
    - name: Lint code
      run: |
        flake8 --ignore=E501,E231 *.py
        pylint --disable=C0301 --disable=C0326 test_app.py
    - name: Run unit tests
      run: |
        python -m unittest --verbose --failfast